name: gps_plus
description: "Cell tower-based positioning as a GPS fallback for Flutter apps."
version: 0.1.0
homepage:

environment:
  sdk: ^3.6.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  sqflite: ^2.4.1
  path_provider: ^2.1.5
  http: ^1.2.2
  latlong2: ^0.9.1
  csv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.navigate.gps_plus
        pluginClass: GpsPlusPlugin
      ios:
        pluginClass: GpsPlusPlugin
      windows:
        pluginClass: GpsPlusPluginCApi
